- name: Setup My Pc ğŸ˜
  hosts: ubuntu_local
  become: yes
  become_method: sudo
  #  connection: local
  gather_facts: no
  roles:
    - environment
    - browsers
    - ide
    - networking
    - terminal
    - system
